---
- name: Create Dirs on remote machine.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ rpm_spingboot_dest }}"
- name : Copy file RPM to remote machine.
  copy:
    src: "files/rpm_spingboot/{{ item }}"
    dest: "{{ rpm_spingboot_dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - "python-chardet-2.2.1-3.el7.noarch.rpm"
    - "python-requests-2.6.0-10.el7.noarch.rpm"
    - "python-urllib3-1.10.2-7.el7.noarch.rpm"
- name: Install RPM
  shell: cd "{{ rpm_spingboot_dest }}";yum install *.rpm -y
- name : Copy file to remote machine.
  copy:
    src: "files/{{ item }}"
    dest: "{{ plugindir }}"
    owner: root
    group: root
    mode: 0775
  with_items:
    - "check_spingboot.py"
##########################################################################
- name: Add line to file vnpay_linux.cfg
  blockinfile:
    path: "{{ includedir }}/vnpay_linux.cfg"
    marker: "####################################"
    state: present
    block: |
      command[check_springboot]=/usr/local/nagios/libexec/check_springboot.py --host 127.0.0.1 --port $ARG1$ --warning $ARG2$ --critical $ARG3$ $ARG4$