---
- name: Create Dirs on remote machine.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ rpm_grafana }}"
- name : Copy file RPM to remote machine.
  copy:
    src: "files/rpm_grafana/{{ item }}"
    dest: "{{ rpm_grafana_dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - "python-chardet-2.2.1-3.el7.noarch.rpm"
- name: Install RPM
  shell: cd "{{ rpm_grafana_dest }}";yum install *.rpm -y
