---
- name: Create Dirs on remote machine.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ rpm_influxdb_dest }}"
    - "{{ rpm_spingboot_dest }}"
- name : Copy file RPM to remote machine.
  copy:
    src: "files/rpm_spingboot/{{ item }}"
    dest: "{{ rpm_spingboot_dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - "python-chardet-2.2.1-3.el7.noarch.rpm"
    - "python-requests-2.6.0-10.el7.noarch.rpm"
    - "python-urllib3-1.10.2-7.el7.noarch.rpm"
#- name: Install RPM
#  shell: cd "{{ rpm_spingboot_dest }}";yum install *.rpm -y
#- name : Copy file RPM to remote machine.
#  copy:
#    src: "files/rpm_influxdb/{{ item }}"
#    dest: "{{ rpm_influxdb_dest }}"
#    owner: root
#    group: root
#    mode: 0755
#  with_items:
#    - "influxdb-1.8.4.x86_64.rpm"
#- name: Install RPM
#  shell: cd "{{ rpm_influxdb_dest }}";yum install *.rpm -y
#- name: Start of service influxdb
#  service: name=influxdb state=started enabled=yes

- name: Create database
  influxdb_database:
#      hostname: "{{influxdb_ip_address}}"
      database_name: 'bidomni'

- name: Create an admin user on a remote host using custom login credentials
  influxdb_user:
    user_name: admin
    user_password: vnpay123
    admin: yes
#    hostname: "{{ influxdb_hostname }}"
#    login_username: "{{ influxdb_username }}"
#    login_password: "{{ influxdb_password }}"

- name: Create a user on localhost with privileges
  influxdb_user:
    user_name: telegraf
    user_password: vnpay123
    login_username: "admin"
    login_password: "vnpay123"
    grants:
      - database: 'bidomni'
        privilege: 'ALL'
- name: create 1 day retention policy
  influxdb_retention_policy:
      hostname: "{{influxdb_ip_address}}"
      database_name: 'bidomni'
      policy_name: test
      duration: 1d
      replication: 1