---
# - name: Create Dirs.
  # file:
    # path: "{{ item }}"
    # state: directory
    # mode: 0755
    # with_items:
       # - "{{ softdir_dest }}"
       # - "{{ opt_sh_dest }}"
#- name: Create file blank
#  file:
#  path: /etc/yum.repos.d/red.repo
#    state: touch
#    owner: root
#    group: root
#    mode: 0600
# - name: Copy file.
  # copy:
    # src: "files/backup.sh"
    # dest: "{{ opt_sh_dest }}"
    # owner: root
    # group: root
    # mode: 0755
# - name: change all file in /etc/yum.repo.d to backup
  # command: sh "{{ opt_sh_dest }}/backup.sh"
- include: "mount_iso.yml"
- name : Copy files.
  copy:
    src: "files/nagiosxi/{{ item }}"
    dest: /tmp
    owner: root
    group: root
    mode: 0775
  with_items:
    - "phantomjs-2.1.1-linux-x86_64.tar.bz2"
    - "wkhtmltox-0.12.1.3.el7.x86_64.rpm"
    - "clear_nagiosxi_dir.sh"
    - "upgrade.sh"
- name: Run script delete nagiosxi old dir in /tmp
  command: sh "{{ tmpdir }}/clear_nagiosxi_dir.sh"
- name: Unpack nagiosxi latest
  unarchive:
    src: files/nagiosxi/xi-latest.tar.gz
    dest: /tmp
- template:
   src: template/install.j2
   dest: "/tmp/nagiosxi/subcomponents/wkhtmltox/install"
   owner: nagios
   group: nagios
   mode: 0755
- template:
   src: template/upgrade.j2
   dest: "/tmp/nagiosxi/upgrade"
   owner: nagios
   group: nagios
   mode: 0755
- name: Run script upgrade
  shell: yes | /tmp/upgrade.sh
