---
- include: "mount_iso.yml"
- name : Copy files.
  copy:
    src: "files/nagiosxi/{{ item }}"
    dest: "{{ tmpdir }}"
    owner: root
    group: root
    mode: 0775
  with_items:
    - "phantomjs-2.1.1-linux-x86_64.tar.bz2"
    - "wkhtmltox-0.12.1.3.el7.x86_64.rpm"
    - "clear_nagiosxi_dir.sh"
    - "upgrade.sh"
- name: Run script delete nagiosxi old dir in /tmp
  command: sh "{{ tmpdir }}/clear_nagiosxi_dir.sh"
- name: Unpack nagiosxi latest
  unarchive:
    src: files/nagiosxi/xi-latest.tar.gz
    dest: "{{ tmpdir }}"
- template:
   src: template/install.j2
   dest: "{{ tmpdir }}/nagiosxi/subcomponents/wkhtmltox/install"
   owner: nagios
   group: nagios
   mode: 0755
- template:
   src: template/upgrade.j2
   dest: "{{ tmpdir }}/nagiosxi/upgrade"
   owner: nagios
   group: nagios
   mode: 0755
- name: Run script upgrade
  shell: yes | /tmp/upgrade.sh
