---
- include: "mount_iso.yml"
- name : Copy files to remote machine.
  copy:
    src: "files/nagiosxi/{{ item }}"
    dest: /store/backups/nagiosxi
    owner: root
    group: root
    mode: 0775
  with_items:
    - "1594982075.tar.gz"
- name : Copy files to remote machine.
  copy:
    src: "files/nagiosxi/{{ item }}"
    dest: "{{ tmpdir }}"
    owner: root
    group: root
    mode: 0775
  with_items:
    - "restore.sh"
- name: Run script restore
  shell: yes | /tmp/restore.sh
- name : Copy files to remote machine.
  copy:
    src: "files/nagiosxi/{{ item }}"
    dest: "{{ tmpdir }}"
    owner: root
    group: root
    mode: 0775
  with_items:
    - "phantomjs-2.1.1-linux-x86_64.tar.bz2"
    - "restore_repair.sh"
    - "wkhtmltox-0.12.1.3.el7.x86_64.rpm"
    - "clear_nagiosxi_dir.sh"
    - "upgrade.sh"
- name: Unpack nagiosxi old to repair
  unarchive:
    src: files/nagiosxi/xi-5.3.3.tar.gz
    dest: "{{ tmpdir }}"
- name: Run script restore repair
  command: sh "{{ tmpdir }}/restore_repair.sh"
- name: Run script delete nagiosxi old dir in tmp
  command: sh "{{ tmpdir }}/clear_nagiosxi_dir.sh"
- name: Unpack nagiosxi latest to remote machine
  unarchive:
    src: files/nagiosxi/xi-latest.tar.gz
    dest: "{{ tmpdir }}"
- template:
   src: template/install.j2
   dest: "{{ tmpdir }}/nagiosxi/subcomponents/wkhtmltox/install"
   owner: nagios
   group: nagios
   mode: 0755
- template:
   src: template/upgrade.j2
   dest: "{{ tmpdir }}/nagiosxi/upgrade"
   owner: nagios
   group: nagios
   mode: 0755
- name: Run script upgrade
  shell: yes | /tmp/upgrade.sh
